name: Olá mundo devops
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Passo 1 - Checkout
        uses: actions/checkout@v4
      - name: Passo 2 - Configuração do Github Pages
        uses: actions/configure-pages@v5
      - name: Passo 3 - Upload no Servidor
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Passo 4 - Deploy
        id: deployment
        uses: actions/deploy-pages@v4
