name: Olá mundo devops
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu_latest
    steps:
      - name: Resgatar o código do git
        uses: action/checkout@v4
