name: Olá mundo devops
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
permissions: 
  id-token: write
  pages: write
  actions: write
  security-events: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: "https://alexfelipe1212.github.io/aula-devops/"
      
    runs-on: ubuntu-latest
    steps:
      - name: Passo 1 - Checkout
        uses: actions/checkout@v4
      - name: Passo 2 - Configuração do Github Pages
        uses: actions/configure-pages@v5
      - name: Passo 3 - Upload no Servidor
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Passo 4 - Deploy
        id: deployment
        uses: actions/deploy-pages@v4
